before_script:
  - composer install

phpstan:php7.2:
  image: php:7.2
  script:
    - vendor/bin/phpstan analyse -c phpstan.neon

phpstan:php7.4:
  image: php:7.4
  script:
    - vendor/bin/phpstan analyse -c phpstan.neon